version: "2.1"
orbs:
  node: circleci/node@5.0.3
  codecov: codecov/codecov@3.2.4
jobs:
  tests:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          node-version: "18.12.1"
      - run: node --version
      - node/install-packages
      - run: 
          name: Run lint check
          command: npm run lint
      - run:
          name:  Run unit tests with coverage
          command: npm run cover
      - codecov/upload:
        file: coverage/*.json
      - run:
          name: Publish to Chromatic
          command: npm run chromatic --project-token=$CHROMATIC_PROJECT_TOKEN
  versioning:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          node-version: "18.12.1"
      - run:
          name: "Check package version"
          command: node scripts/check-version CarolinaMoraes feira-livre
workflows:
  ci:
    jobs:
      - tests
      - versioning:
          filters:
            branches:
              ignore: main
            tags:
              ignore: /.*/
