version: "2.1"
orbs:
  node: circleci/node@5.0.3
jobs:
  tests:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          node-version: "18.12.1"
      - run: node --version
      - node/install-packages
      - run: npm run lint
workflows:
  ci:
    jobs:
      - tests
